"use client";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const noFooterPages = [
    "/admin/dashboard",
    "/agent/dashboard",
    "/rider/dashboard",
    "/admin/users",
    "/admin/agents",
    "/admin/shopowner",
    "/shopowner/dashboard",
    "/shopowner/total-sales",
    "/shopowner/total-orders",
    "/shopowner/total-customers",
    "/shopowner/pending-orders",
    "/shopowner/completed-orders",
    
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        {!noFooterPages.includes(pathname) && <Footer />}
      </body>
    </html>
  );
}
